# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CWW_alpha.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(601, 800)
        Form.setAutoFillBackground(False)
        Form.setStyleSheet("")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(0, 0, 600, 800))
        self.label.setStyleSheet("")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/backgrounds/done_backgrounds/First_Menu.png"))
        self.label.setObjectName("label")
        self.lblText1 = QtWidgets.QLabel(Form)
        self.lblText1.setGeometry(QtCore.QRect(300, 96, 201, 81))
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lblText1.setFont(font)
        self.lblText1.setStyleSheet("position: absolute;\n"
"width: 220px;\n"
"height: 74px;\n"
"left: 673px;\n"
"top: 362px;\n"
"\n"
"font-family: \'Inter\';\n"
"font-style: normal;\n"
"font-weight: 400;\n"
"font-size: 16px;\n"
"line-height: 100%;\n"
"/* or 16px */\n"
"\n"
"display: flex;\n"
"align-items: center;\n"
"text-align: center;\n"
"letter-spacing: 0.1em;\n"
"\n"
"color: #000000;\n"
"")
        self.lblText1.setObjectName("lblText1")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(120, 590, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(99)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("position: absolute;\n"
"width: 160px;\n"
"height: 28px;\n"
"left: 104px;\n"
"top: 598px;\n"
"\n"
"font-family: \'Inter\';\n"
"font-style: normal;\n"
"font-weight: 900;\n"
"font-size: 30px;\n"
"line-height: 100%;\n"
"\n"
"display: flex;\n"
"align-items: center;\n"
"text-align: center;\n"
"letter-spacing: 0.1em;\n"
"")
        self.label_3.setObjectName("label_3")
        self.btnSetSize1 = QtWidgets.QPushButton(Form)
        self.btnSetSize1.setGeometry(QtCore.QRect(90, 695, 122, 80))
        self.btnSetSize1.setStyleSheet("position: absolute;\n"
"width: 122px;\n"
"height: 80px;\n"
"left: 0.35px;\n"
"top: 0.53px;\n"
"\n"
"font-family: \'Inter\';\n"
"font-style: normal;\n"
"font-weight: 600;\n"
"font-size: 20px;\n"
"line-height: 100%;\n"
"/* or 24px */\n"
"\n"
"display: flex;\n"
"align-items: center;\n"
"text-align: center;\n"
"letter-spacing: 0.1em;\n"
"\n"
"color: #FFFFFF;\n"
"\n"
"mix-blend-mode: difference;\n"
"border: 4px solid #FFE3E3;\n"
"filter: drop-shadow(0px 0px 20px rgba(250, 237, 190, 0.85));\n"
"border-radius: 20px;")
        self.btnSetSize1.setObjectName("btnSetSize1")
        self.btnSetSize2 = QtWidgets.QPushButton(Form)
        self.btnSetSize2.setGeometry(QtCore.QRect(240, 695, 122, 80))
        self.btnSetSize2.setStyleSheet("position: absolute;\n"
"width: 122px;\n"
"height: 80px;\n"
"left: 0.35px;\n"
"top: 0.53px;\n"
"\n"
"font-family: \'Inter\';\n"
"font-style: normal;\n"
"font-weight: 600;\n"
"font-size: 20px;\n"
"line-height: 100%;\n"
"/* or 24px */\n"
"\n"
"display: flex;\n"
"align-items: center;\n"
"text-align: center;\n"
"letter-spacing: 0.1em;\n"
"\n"
"color: #FFFFFF;\n"
"\n"
"mix-blend-mode: difference;\n"
"border: 4px solid #FFE3E3;\n"
"filter: drop-shadow(0px 0px 20px rgba(250, 237, 190, 0.85));\n"
"border-radius: 20px;")
        self.btnSetSize2.setObjectName("btnSetSize2")
        self.btnSetSize3 = QtWidgets.QPushButton(Form)
        self.btnSetSize3.setGeometry(QtCore.QRect(390, 695, 122, 80))
        self.btnSetSize3.setStyleSheet("position: absolute;\n"
"width: 122px;\n"
"height: 80px;\n"
"left: 0.35px;\n"
"top: 0.53px;\n"
"\n"
"font-family: \'Inter\';\n"
"font-style: normal;\n"
"font-weight: 600;\n"
"font-size: 20px;\n"
"line-height: 100%;\n"
"/* or 24px */\n"
"\n"
"display: flex;\n"
"align-items: center;\n"
"text-align: center;\n"
"letter-spacing: 0.1em;\n"
"\n"
"color: #FFFFFF;\n"
"\n"
"mix-blend-mode: difference;\n"
"border: 4px solid #FFE3E3;\n"
"filter: drop-shadow(0px 0px 20px rgba(250, 237, 190, 0.85));\n"
"border-radius: 20px;")
        self.btnSetSize3.setObjectName("btnSetSize3")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(296, 500, 112, 32))
        self.label_4.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("position: absolute;\n"
"width: 116px;\n"
"height: 30px;\n"
"left: 282px;\n"
"top: 508px;\n"
"\n"
"font-style: normal;\n"
"font-weight: 400;\n"
"font-size: 32px;\n"
"line-height: 100%;\n"
"/* or 36px */\n"
"\n"
"display: flex;\n"
"align-items: center;\n"
"\n"
"-webkit-background-clip: text;\n"
"-webkit-text-fill-color: transparent;\n"
"background-clip: text;\n"
"text-fill-color: transparent;")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(0, 80, 600, 191))
        self.label_5.setStyleSheet("position: absolute;\n"
"width: 600px;\n"
"height: 80px;\n"
"left: 378px;\n"
"top: 359px;\n"
"\n"
"background: rgba(255, 255, 255, 0.4);\n"
"mix-blend-mode: soft-light;")
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.btnSettings = QtWidgets.QPushButton(Form)
        self.btnSettings.setEnabled(True)
        self.btnSettings.setGeometry(QtCore.QRect(15, 8, 30, 30))
        font = QtGui.QFont()
        font.setKerning(True)
        self.btnSettings.setFont(font)
        self.btnSettings.setAutoFillBackground(False)
        self.btnSettings.setStyleSheet("border: none;\n"
"background-color: rgba(255, 255, 255, 0);")
        self.btnSettings.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../resources/icons/bootstrap-icons-1.9.1/gear.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnSettings.setIcon(icon)
        self.btnSettings.setIconSize(QtCore.QSize(22, 22))
        self.btnSettings.setShortcut("")
        self.btnSettings.setCheckable(False)
        self.btnSettings.setAutoExclusive(False)
        self.btnSettings.setAutoRepeatDelay(300)
        self.btnSettings.setObjectName("btnSettings")
        self.btnInfo = QtWidgets.QPushButton(Form)
        self.btnInfo.setEnabled(True)
        self.btnInfo.setGeometry(QtCore.QRect(510, 116, 40, 40))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setKerning(False)
        self.btnInfo.setFont(font)
        self.btnInfo.setAutoFillBackground(False)
        self.btnInfo.setStyleSheet("border: none;\n"
"background-color: rgba(255, 255, 255, 0);")
        self.btnInfo.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../resources/icons/project_icons/info-circle1.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnInfo.setIcon(icon1)
        self.btnInfo.setIconSize(QtCore.QSize(36, 36))
        self.btnInfo.setCheckable(False)
        self.btnInfo.setObjectName("btnInfo")
        self.btnShowMenu = QtWidgets.QPushButton(Form)
        self.btnShowMenu.setGeometry(QtCore.QRect(580, 12, 20, 20))
        self.btnShowMenu.setStyleSheet("border: none;\n"
"background-color: rgba(255, 255, 255, 0);")
        self.btnShowMenu.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../resources/icons/bootstrap-icons-1.9.1/eye-slash.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnShowMenu.setIcon(icon2)
        self.btnShowMenu.setIconSize(QtCore.QSize(20, 20))
        self.btnShowMenu.setCheckable(False)
        self.btnShowMenu.setObjectName("btnShowMenu")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(0, 0, 600, 44))
        self.label_6.setStyleSheet("border: none;\n"
"background-size: 120px 120px;\n"
"/*width: 160px;\n"
"height:160px;*/\n"
"background-color: rgba(255, 255, 255, 0.4);")
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.lblTime = QtWidgets.QLabel(Form)
        self.lblTime.setGeometry(QtCore.QRect(50, 12, 66, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lblTime.setFont(font)
        self.lblTime.setObjectName("lblTime")
        self.lblBattery = QtWidgets.QLabel(Form)
        self.lblBattery.setGeometry(QtCore.QRect(126, 10, 24, 24))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.lblBattery.setFont(font)
        self.lblBattery.setStyleSheet("body {\n"
"    background-image: url(:/newPrefix/bootstrap-icons-1.9.1/battery-full.svg);\n"
"    background-size: cover;\n"
"};\n"
"body.stretch {\n"
"    width:100%;\n"
"    height:100%;\n"
"}\n"
"border: none;\n"
"background-color: rgba(255, 255, 255, 0);")
        self.lblBattery.setText("")
        self.lblBattery.setTextFormat(QtCore.Qt.AutoText)
        self.lblBattery.setPixmap(QtGui.QPixmap("../resources/icons/bootstrap-icons-1.9.1/battery-full.svg"))
        self.lblBattery.setScaledContents(False)
        self.lblBattery.setAlignment(QtCore.Qt.AlignCenter)
        self.lblBattery.setWordWrap(False)
        self.lblBattery.setObjectName("lblBattery")
        self.lblText1_2 = QtWidgets.QLabel(Form)
        self.lblText1_2.setGeometry(QtCore.QRect(320, 210, 181, 40))
        font = QtGui.QFont()
        font.setFamily("Inter")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.lblText1_2.setFont(font)
        self.lblText1_2.setStyleSheet("position: absolute;\n"
"width: 220px;\n"
"height: 74px;\n"
"left: 673px;\n"
"top: 362px;\n"
"\n"
"font-family: \'Inter\';\n"
"font-style: normal;\n"
"font-weight: 400;\n"
"font-size: 16px;\n"
"line-height: 100%;\n"
"/* or 16px */\n"
"\n"
"display: flex;\n"
"align-items: center;\n"
"text-align: center;\n"
"letter-spacing: 0.1em;\n"
"\n"
"color: #000000;\n"
"")
        self.lblText1_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblText1_2.setObjectName("lblText1_2")
        self.label.raise_()
        self.label_6.raise_()
        self.label_5.raise_()
        self.lblText1.raise_()
        self.label_3.raise_()
        self.btnSetSize1.raise_()
        self.btnSetSize2.raise_()
        self.btnSetSize3.raise_()
        self.label_4.raise_()
        self.lblTime.raise_()
        self.lblBattery.raise_()
        self.btnShowMenu.raise_()
        self.btnSettings.raise_()
        self.btnInfo.raise_()
        self.lblText1_2.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.lblText1.setText(_translate("Form", "Мы не предоставляем\n"
"информацию о вас\n"
"треьтим лицам, кроме\n"
"наших разработчиков"))
        self.label_3.setText(_translate("Form", "Profiles:"))
        self.btnSetSize1.setText(_translate("Form", "480x\n"
"640px"))
        self.btnSetSize2.setText(_translate("Form", "540x\n"
"720px"))
        self.btnSetSize3.setText(_translate("Form", "600x\n"
"800px"))
        self.label_4.setText(_translate("Form", "Готово!"))
        self.lblTime.setText(_translate("Form", "Time"))
        self.lblText1_2.setText(_translate("Form", "Единицы измерения:"))

import PyQt5_Project_beta.resources.images.wtf.py
import PyQt5_Project_beta.resources.icons.work_icons
# import ../resources.icons.icons.qrc
# import screens.icons_rc
# import screens.wtf_rc
